[package]
name = "mhw-sticker-helper"
version = "1.0.0"
edition = "2021"

[dependencies]
tex-convert = { path = "../../crates/tex-convert", features = [
    "tex2dds",
    "dds2tex",
] }
image = { version = "0.25", default-features = false, features = ["png"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
dialoguer = "0.11"
rust-embed = "8.5"
ring = { version = "0.17", features = ["std"] }
zip = { version = "2.2", no_default_features = true, features = ["deflate"] }

[build-dependencies]
winres = "0.1"